import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, Clock3, RefreshCw, ShieldCheck, UsersRound } from "lucide-react";

export function AdminAccessLogs() {
  const query = trpc.auth.accessLogs.useQuery({ limit: 250 }, { refetchInterval: 60_000, refetchOnWindowFocus: false });
  if (query.isLoading) return <div className="grid min-h-[420px] place-items-center rounded-3xl border border-white/10 bg-[#0a1725]"><RefreshCw className="h-6 w-6 animate-spin text-cyan-200" /></div>;
  if (query.error) return <div className="rounded-3xl border border-rose-300/20 bg-rose-300/5 p-6 text-rose-100"><p className="font-semibold">Não foi possível carregar os acessos.</p><Button variant="outline" className="mt-4 border-rose-200/20" onClick={() => query.refetch()}>Tentar novamente</Button></div>;

  const rows = query.data ?? [];
  const today = new Date().toLocaleDateString("pt-BR", { timeZone: "America/Sao_Paulo" });
  const todayRows = rows.filter(row => new Date(row.createdAt).toLocaleDateString("pt-BR", { timeZone: "America/Sao_Paulo" }) === today);
  const successes = todayRows.filter(row => row.result === "success").length;
  const failures = todayRows.filter(row => row.result === "failure").length;
  const uniqueUsers = new Set(todayRows.filter(row => row.result === "success").map(row => row.username)).size;

  return <div className="mx-auto max-w-[1600px] space-y-6 pb-10">
    <header className="overflow-hidden rounded-[28px] border border-cyan-200/15 bg-[radial-gradient(circle_at_85%_12%,rgba(34,211,238,.15),transparent_30%),linear-gradient(135deg,#071421,#091a2b_55%,#06111c)] p-6 shadow-2xl shadow-cyan-950/20">
      <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-cyan-200" /><span className="font-mono-ui text-[10px] uppercase tracking-[.2em] text-cyan-100/65">Administração · auditoria</span></div><h1 className="mt-4 text-3xl font-black tracking-[-.045em] text-white sm:text-4xl">Histórico de acessos</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Tentativas e acessos ao dashboard, disponíveis exclusivamente para o administrador.</p></div><Button variant="outline" onClick={() => query.refetch()} className="border-white/10 bg-white/[.04] text-white"><RefreshCw className="mr-2 h-4 w-4" />Atualizar</Button></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-3"><AccessKpi label="Acessos hoje" value={successes.toLocaleString("pt-BR")} icon={CheckCircle2} tone="emerald" /><AccessKpi label="Usuários hoje" value={uniqueUsers.toLocaleString("pt-BR")} icon={UsersRound} tone="cyan" /><AccessKpi label="Falhas hoje" value={failures.toLocaleString("pt-BR")} icon={AlertTriangle} tone="rose" /></div>
    </header>
    <section className="rounded-3xl border border-white/10 bg-[#0a1725] p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-cyan-200/60">Últimos registros</p><h2 className="mt-2 text-xl font-bold text-white">Atividade de autenticação</h2></div><Badge variant="outline" className="border-white/10 text-slate-300">{rows.length} registros</Badge></div><div className="premium-scrollbar mt-5 max-h-[680px] overflow-auto rounded-2xl border border-white/8"><table className="w-full min-w-[900px] text-left text-sm"><thead className="sticky top-0 z-10 bg-[#0b1928] text-[10px] uppercase tracking-[.12em] text-slate-500"><tr><th className="px-4 py-3">Usuário</th><th className="px-4 py-3">Resultado</th><th className="px-4 py-3">Data e hora</th><th className="px-4 py-3">IP</th><th className="px-4 py-3">Navegador / dispositivo</th></tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-t border-white/6 text-slate-300"><td className="px-4 py-3 font-medium text-white">{row.username}</td><td className="px-4 py-3"><ResultBadge result={row.result} /></td><td className="whitespace-nowrap px-4 py-3 font-mono-ui text-xs">{new Date(row.createdAt).toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" })}</td><td className="px-4 py-3 font-mono-ui text-xs">{row.ipAddress || "Não disponível"}</td><td className="max-w-[380px] truncate px-4 py-3 text-xs text-slate-500" title={row.userAgent || undefined}>{row.userAgent || "Não disponível"}</td></tr>)}</tbody></table>{rows.length === 0 ? <div className="grid min-h-48 place-items-center text-sm text-slate-500"><Clock3 className="mb-2 h-5 w-5" />Nenhum acesso registrado.</div> : null}</div></section>
  </div>;
}

function AccessKpi({ label, value, icon: Icon, tone }: { label: string; value: string; icon: typeof ShieldCheck; tone: "cyan" | "emerald" | "rose" }) { const color = tone === "cyan" ? "text-cyan-200 bg-cyan-300/10 border-cyan-300/15" : tone === "emerald" ? "text-emerald-200 bg-emerald-300/10 border-emerald-300/15" : "text-rose-200 bg-rose-300/10 border-rose-300/15"; return <div className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className={`grid h-8 w-8 place-items-center rounded-xl border ${color}`}><Icon className="h-4 w-4" /></div><p className="mt-4 font-mono-ui text-[9px] uppercase tracking-[.14em] text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-white">{value}</p></div>; }
function ResultBadge({ result }: { result: "success" | "failure" | "logout" }) { const classes = result === "success" ? "border-emerald-300/20 bg-emerald-300/10 text-emerald-100" : result === "failure" ? "border-rose-300/20 bg-rose-300/10 text-rose-100" : "border-slate-300/15 bg-slate-300/5 text-slate-300"; const label = result === "success" ? "Acesso autorizado" : result === "failure" ? "Tentativa negada" : "Sessão encerrada"; return <Badge variant="outline" className={classes}>{label}</Badge>; }
