import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Activity, BarChart3, BriefcaseBusiness, CalendarDays, CheckCircle2, CircleDollarSign, Database, Filter, Gauge, Layers3, Lightbulb, Target, UserRound, Workflow, X } from "lucide-react";
import { useMemo, useState } from "react";

type CountRow = { label: string; count: number };
type FilterOption = { value: string; label: string; count: number };
type Filters = { pipeline: string; responsible: string; source: string; stage: string; position: string; product: string };

const DEFAULT_FILTERS: Filters = { pipeline: "all", responsible: "all", source: "all", stage: "all", position: "all", product: "all" };
const integer = (value: number) => Math.round(value || 0).toLocaleString("pt-BR");
const percentage = (value: number, total: number) => total ? `${((value / total) * 100).toFixed(1).replace(".", ",")}%` : "0,0%";
const brl = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 }).format(value || 0);

export function BitrixRdOpportunityDashboard() {
  const [startDate, setStartDate] = useState("2026-08-01");
  const [endDate, setEndDate] = useState("2026-08-19");
  const [draftStart, setDraftStart] = useState(startDate);
  const [draftEnd, setDraftEnd] = useState(endDate);
  const [filters, setFilters] = useState<Filters>(DEFAULT_FILTERS);
  const query = trpc.bitrix24.rdOpportunityDashboard.useQuery({ startDate, endDate, ...filters }, { refetchInterval: 60_000 });
  const data = query.data;
  const activeFilterCount = Object.values(filters).filter(value => value !== "all").length;

  const insights = useMemo(() => {
    if (!data || !data.totals.leads) return [];
    const topStage = data.stages[0];
    const topResponsible = data.responsible[0];
    const missingProduct = data.totals.leads - data.coverage.product;
    return [
      { label: "Pico de entrada", value: data.totals.peakDay ? `${data.totals.peakDay.date.split("-").reverse().join("/")} · ${integer(data.totals.peakDay.count)} leads` : "Sem movimento", detail: "Maior volume diário no cruzamento atual." },
      { label: "Etapa dominante", value: topStage ? `${topStage.label} · ${percentage(topStage.count, data.totals.leads)}` : "Não identificada", detail: "Concentração atual do estoque de leads." },
      { label: "Maior carteira", value: topResponsible ? `${topResponsible.label} · ${integer(topResponsible.count)}` : "Não identificada", detail: "Responsável com mais leads dentro dos filtros." },
      { label: "Produto não informado", value: `${integer(missingProduct)} leads`, detail: `${percentage(missingProduct, data.totals.leads)} do recorte sem produto preenchido.` },
    ];
  }, [data]);

  const applyDates = () => {
    if (draftStart > draftEnd) return;
    setStartDate(draftStart);
    setEndDate(draftEnd);
  };
  const updateFilter = (key: keyof Filters, value: string) => setFilters(current => ({ ...current, [key]: value }));

  if (query.isLoading && !data) return <LoadingState />;
  if (query.isError) return <EmptyState title="Não foi possível carregar Negócios" detail={query.error.message || "A consulta gerencial não respondeu."} />;
  if (!data) return <EmptyState title="Visão gerencial indisponível" detail="Não houve retorno para o recorte selecionado." />;
  const filterOptions = data.filterOptions ?? { pipelines: [], responsibles: [], sources: [], stages: [], positions: [], products: [] };
  const wonDeals = data.wonDeals ?? { totalInDateRange: 0, valueInDateRange: 0, linkedToFilteredLeads: 0, linkedValue: 0, outsideCurrentLeadFilter: 0, linkCoverage: 0, byCloseDay: [], byOrigin: [], linkedByCloseDay: [], linkedByOrigin: [] };

  return <div className="space-y-5">
    <section className="overflow-hidden rounded-3xl border border-cyan-200/15 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,.14),transparent_36%),linear-gradient(135deg,rgba(9,28,45,.98),rgba(7,17,29,.96))] p-5 sm:p-6">
      <div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end">
        <div className="max-w-3xl"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className="border-cyan-200/20 bg-cyan-200/[.06] text-cyan-100">Negócios · Bitrix24</Badge><Badge variant="outline" className="border-emerald-200/20 bg-emerald-200/[.05] text-emerald-100">Evento excluído</Badge><Badge variant="outline" className="border-white/10 text-white/65">{activeFilterCount} filtros cruzados</Badge></div><h3 className="mt-4 text-2xl font-black tracking-[-.04em] text-white sm:text-3xl">Oportunidades e fechamentos</h3><p className="mt-2 text-sm leading-6 text-slate-300">Leads com <strong>Nome do Lead = Oportunidade do RD Station</strong>. O período recalcula entradas e fechamentos; os filtros dimensionais cruzam os leads. A cobertura por LEAD_ID permanece separada e auditável.</p></div>
        <div className="grid gap-3 sm:grid-cols-2 xl:min-w-[550px] xl:grid-cols-[1fr_1fr_auto]"><DateField label="Data inicial" value={draftStart} onChange={setDraftStart} max="2026-08-19" /><DateField label="Data final" value={draftEnd} onChange={setDraftEnd} min={draftStart} max="2026-08-19" /><Button onClick={applyDates} disabled={draftStart > draftEnd} className="h-11 self-end bg-white text-slate-950 hover:bg-slate-100"><Filter className="mr-2 h-4 w-4" />Aplicar</Button></div>
      </div>
      <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><ManagerKpi icon={Layers3} label="Leads no filtro" value={integer(data.totals.leads)} helper="Título exato e Evento excluído" tone="cyan" /><ManagerKpi icon={CalendarDays} label="Dias com entrada" value={integer(data.totals.activeDays)} helper={`${data.period.start.split("-").reverse().join("/")} a ${data.period.end.split("-").reverse().join("/")}`} tone="violet" /><ManagerKpi icon={Gauge} label="Média por dia ativo" value={data.totals.averagePerActiveDay.toFixed(1).replace(".", ",")} helper="Sem estimar dias sem entrada" tone="emerald" /><ManagerKpi icon={CheckCircle2} label="Vendas vinculadas" value={integer(wonDeals.linkedToFilteredLeads)} helper={`${percentage(wonDeals.linkedToFilteredLeads, wonDeals.totalInDateRange)} dos ganhos têm LEAD_ID utilizável`} tone="amber" /><ManagerKpi icon={CircleDollarSign} label="Valor vinculado" value={brl(wonDeals.linkedValue)} helper="Somente LEAD_ID exato" tone="emerald" /></div>
    </section>

    <section className="rounded-2xl border border-white/10 bg-black/15 p-5"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><PanelHeader eyebrow="Filtros cruzados" title="Refine a leitura comercial" detail="Pipeline, responsável, fonte, etapa, posição e produto recalculam a análise dos leads. Fechamentos continuam pelo período, com vínculo destacado quando houver LEAD_ID." />{activeFilterCount ? <Button variant="outline" size="sm" className="w-fit border-white/10 bg-black/10 text-muted-foreground" onClick={() => setFilters(DEFAULT_FILTERS)}><X className="mr-2 h-3.5 w-3.5" />Limpar {activeFilterCount} filtros</Button> : null}</div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><FilterSelect label="Pipeline de Vendas" value={filters.pipeline} options={filterOptions.pipelines} onChange={value => updateFilter("pipeline", value)} /><FilterSelect label="Responsável" value={filters.responsible} options={filterOptions.responsibles} onChange={value => updateFilter("responsible", value)} /><FilterSelect label="Informações da fonte" value={filters.source} options={filterOptions.sources} onChange={value => updateFilter("source", value)} /><FilterSelect label="Etapa" value={filters.stage} options={filterOptions.stages} onChange={value => updateFilter("stage", value)} /><FilterSelect label="Posição" value={filters.position} options={filterOptions.positions} onChange={value => updateFilter("position", value)} /><FilterSelect label="Produto de Interesse" value={filters.product} options={filterOptions.products} onChange={value => updateFilter("product", value)} /></div></section>

    {data.totals.leads === 0 ? <EmptyState title="Nenhum lead encontrado" detail="Ajuste as datas ou limpe parte dos filtros cruzados." /> : <>
      <section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><LeadDailyChart rows={data.byDay} /><RankPanel eyebrow="Fluxo comercial" title="Leads por etapa" rows={data.stages} total={data.totals.leads} tone="violet" /></section>
      <section className="grid gap-5 xl:grid-cols-2"><RankPanel eyebrow="Responsabilidade" title="Leads por responsável" rows={data.responsible} total={data.totals.leads} tone="cyan" /><RankPanel eyebrow="Origem declarada" title="Informações da fonte" rows={data.sourceInformation} total={data.totals.leads} tone="emerald" /></section>

      <section className="overflow-hidden rounded-2xl border border-emerald-200/15 bg-[linear-gradient(135deg,rgba(52,211,153,.075),rgba(52,211,153,.015))] p-5"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><PanelHeader eyebrow="Fechamentos" title="Negócios ganhos por data e origem" detail="CLOSEDATE e origem vêm diretamente do negócio. O vínculo com os filtros de lead é mostrado separadamente e exige LEAD_ID exato." /><Badge variant="outline" className="w-fit border-emerald-200/20 text-emerald-100">{integer(wonDeals.outsideCurrentLeadFilter)} sem LEAD_ID vinculável</Badge></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SalesKpi label="Ganhos no período" value={integer(wonDeals.totalInDateRange)} helper={brl(wonDeals.valueInDateRange)} /><SalesKpi label="Ganhos vinculados" value={integer(wonDeals.linkedToFilteredLeads)} helper="LEAD_ID exato e filtros compatíveis" /><SalesKpi label="Valor vinculado" value={brl(wonDeals.linkedValue)} helper="Sem atribuir receita sem vínculo" /><SalesKpi label="Cobertura do vínculo" value={`${wonDeals.linkCoverage.toFixed(1).replace(".", ",")}%`} helper="Ganhos vinculados ÷ ganhos no período" /></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><WonDailyChart rows={wonDeals.byCloseDay} /><RankPanel eyebrow="Origem do negócio" title="Ganhos por origem declarada" rows={wonDeals.byOrigin} total={Math.max(1, wonDeals.totalInDateRange)} tone="emerald" /></div></section>

      <section className="rounded-2xl border border-white/10 bg-black/15 p-5"><PanelHeader eyebrow="Qualidade do cadastro" title="Cobertura dos campos gerenciais" detail="Percentual de leads com informação utilizável no cruzamento atual." /><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><CoverageCard label="Informações da fonte" value={data.coverage.sourceInformation} total={data.totals.leads} icon={Database} /><CoverageCard label="Posição" value={data.coverage.position} total={data.totals.leads} icon={Activity} /><CoverageCard label="Produto de Interesse" value={data.coverage.product} total={data.totals.leads} icon={Target} /><CoverageCard label="Responsável com nome" value={data.coverage.responsibleName} total={data.totals.leads} icon={UserRound} /></div></section>
      <section className="grid gap-5 xl:grid-cols-2"><RankPanel eyebrow="Perfil" title="Posição" rows={data.positions} total={data.totals.leads} tone="amber" limit={10} /><RankPanel eyebrow="Interesse" title="Produto de Interesse" rows={data.products} total={data.totals.leads} tone="cyan" limit={10} /></section>
      <section className="rounded-2xl border border-amber-200/15 bg-[linear-gradient(135deg,rgba(251,191,36,.07),rgba(251,191,36,.015))] p-5"><div className="flex items-center gap-2"><Lightbulb className="h-4 w-4 text-amber-200" /><p className="font-mono-ui text-[10px] uppercase tracking-[.16em] text-amber-100/75">Insights gerenciais</p></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{insights.map(item => <article key={item.label} className="rounded-xl border border-amber-100/10 bg-black/15 p-4"><p className="text-[10px] uppercase tracking-[.12em] text-amber-100/65">{item.label}</p><p className="mt-2 text-base font-bold text-white">{item.value}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.detail}</p></article>)}</div></section>
      <section className="flex flex-col justify-between gap-3 rounded-2xl border border-white/8 bg-white/[.02] p-4 text-xs leading-5 text-muted-foreground md:flex-row md:items-center"><span>Critério: título exato “{data.titleFilter}” · origem Evento excluída.</span><span>Ganhos sem LEAD_ID não recebem origem presumida e permanecem fora do cruzamento.</span></section>
    </>}
  </div>;
}

function DateField({ label, value, onChange, min, max }: { label: string; value: string; onChange: (value: string) => void; min?: string; max?: string }) { return <label><span className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-white/55">{label}</span><input aria-label={label} type="date" value={value} min={min} max={max} onChange={event => onChange(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-[#08131f] px-3 text-sm text-white outline-none focus:ring-2 focus:ring-cyan-200/35" /></label>; }
function FilterSelect({ label, value, options, onChange }: { label: string; value: string; options: FilterOption[]; onChange: (value: string) => void }) { return <label><span className="font-mono-ui text-[10px] uppercase tracking-[.12em] text-muted-foreground">{label}</span><select aria-label={`Filtrar por ${label}`} value={value} onChange={event => onChange(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-[#08131f] px-3 text-sm text-white outline-none focus:ring-2 focus:ring-cyan-200/35"><option value="all">Todos · {options.reduce((sum, item) => sum + item.count, 0)}</option>{options.map(item => <option key={item.value} value={item.value}>{item.label} · {integer(item.count)}</option>)}</select></label>; }
function ManagerKpi({ icon: Icon, label, value, helper, tone }: { icon: typeof Layers3; label: string; value: string; helper: string; tone: "cyan" | "violet" | "emerald" | "amber" }) { const colors = { cyan: "text-cyan-200 bg-cyan-200/10", violet: "text-violet-200 bg-violet-200/10", emerald: "text-emerald-200 bg-emerald-200/10", amber: "text-amber-200 bg-amber-200/10" }; return <article className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-mono-ui text-[9px] uppercase tracking-[.14em] text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-black tracking-tight text-white">{value}</p></div><span className={`grid h-9 w-9 place-items-center rounded-xl ${colors[tone]}`}><Icon className="h-4 w-4" /></span></div><p className="mt-3 text-xs text-muted-foreground">{helper}</p></article>; }
function SalesKpi({ label, value, helper }: { label: string; value: string; helper: string }) { return <article className="rounded-xl border border-emerald-100/10 bg-black/15 p-4"><p className="font-mono-ui text-[9px] uppercase tracking-[.13em] text-emerald-100/60">{label}</p><p className="mt-2 text-2xl font-black text-white">{value}</p><p className="mt-2 text-xs text-muted-foreground">{helper}</p></article>; }
function PanelHeader({ eyebrow, title, detail }: { eyebrow: string; title: string; detail: string }) { return <div><p className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-cyan-100/60">{eyebrow}</p><h4 className="mt-1 text-lg font-bold text-white">{title}</h4><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div>; }

function LeadDailyChart({ rows }: { rows: { date: string; count: number }[] }) { const max = Math.max(1, ...rows.map(item => item.count)); return <div className="rounded-2xl border border-white/10 bg-black/15 p-5"><PanelHeader eyebrow="Volume diário" title="Leads por dia" detail="Entrada de oportunidades no fuso de São Paulo." /><div className="mt-6 overflow-x-auto pb-2"><div className="flex min-w-[680px] items-end gap-2" role="img" aria-label="Gráfico de barras de leads por dia">{rows.map(item => <div key={item.date} className="group flex min-w-7 flex-1 flex-col items-center gap-2"><span className="font-mono-ui text-[10px] text-cyan-100 opacity-0 transition-opacity group-hover:opacity-100">{item.count}</span><div className="w-full rounded-t-lg bg-[linear-gradient(180deg,#67e8f9,#0891b2)] transition-transform duration-200 group-hover:-translate-y-1" style={{ height: `${Math.max(10, (item.count / max) * 180)}px` }} /><span className="rotate-[-45deg] whitespace-nowrap text-[9px] text-muted-foreground">{item.date.slice(8, 10)}/{item.date.slice(5, 7)}</span></div>)}</div></div></div>; }
function WonDailyChart({ rows }: { rows: { date: string; count: number }[] }) { const max = Math.max(1, ...rows.map(item => item.count)); return <div className="rounded-xl border border-emerald-100/10 bg-black/15 p-4"><PanelHeader eyebrow="Data de fechamento" title="Negócios ganhos por dia" detail="CLOSEDATE e status ganho lidos diretamente do negócio." />{rows.length ? <div className="mt-6 flex min-h-44 items-end gap-2 overflow-x-auto pb-2">{rows.map(item => <div key={item.date} className="flex min-w-12 flex-1 flex-col items-center gap-2"><span className="font-mono-ui text-[10px] text-emerald-100">{item.count}</span><div className="w-full rounded-t-lg bg-[linear-gradient(180deg,#86efac,#059669)]" style={{ height: `${Math.max(12, (item.count / max) * 120)}px` }} /><span className="text-[9px] text-muted-foreground">{item.date.slice(8, 10)}/{item.date.slice(5, 7)}</span></div>)}</div> : <p className="mt-6 text-sm text-muted-foreground">Nenhum negócio ganho no período selecionado.</p>}</div>; }

function RankPanel({ eyebrow, title, rows, total, tone, limit = 10 }: { eyebrow: string; title: string; rows: CountRow[]; total: number; tone: "cyan" | "violet" | "emerald" | "amber"; limit?: number }) { const max = Math.max(1, ...rows.map(item => item.count)); const bar = { cyan: "bg-cyan-300", violet: "bg-violet-300", emerald: "bg-emerald-300", amber: "bg-amber-300" }[tone]; return <div className="rounded-2xl border border-white/10 bg-black/15 p-5"><PanelHeader eyebrow={eyebrow} title={title} detail="Distribuição dentro do cruzamento atual." /><div className="mt-5 space-y-3">{rows.length ? rows.slice(0, limit).map(item => <div key={item.label}><div className="mb-1.5 flex items-center justify-between gap-3"><span className="truncate text-sm text-slate-300" title={item.label}>{item.label}</span><span className="shrink-0 font-mono-ui text-xs text-white">{integer(item.count)} · {percentage(item.count, total)}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/5"><div className={`h-full rounded-full ${bar}`} style={{ width: `${Math.max(2, (item.count / max) * 100)}%` }} /></div></div>) : <p className="text-sm text-muted-foreground">Sem registros identificáveis.</p>}</div></div>; }
function CoverageCard({ label, value, total, icon: Icon }: { label: string; value: number; total: number; icon: typeof Filter }) { const rate = total ? (value / total) * 100 : 0; return <article className="rounded-xl border border-white/8 bg-white/[.02] p-4"><div className="flex items-center justify-between"><Icon className="h-4 w-4 text-cyan-200" /><span className="font-mono-ui text-xs text-cyan-100">{percentage(value, total)}</span></div><p className="mt-4 text-sm font-semibold text-white">{label}</p><p className="mt-1 text-xs text-muted-foreground">{integer(value)} de {integer(total)} leads</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-[linear-gradient(90deg,#22d3ee,#34d399)]" style={{ width: `${rate}%` }} /></div></article>; }
function LoadingState() { return <section className="grid min-h-[420px] place-items-center rounded-2xl border border-white/10 bg-black/15"><div className="text-center"><BriefcaseBusiness className="mx-auto h-7 w-7 animate-pulse text-cyan-200" /><p className="mt-3 text-sm text-muted-foreground">Montando a visão gerencial de Negócios…</p></div></section>; }
function EmptyState({ title, detail }: { title: string; detail: string }) { return <section className="grid min-h-64 place-items-center rounded-2xl border border-white/10 bg-black/15 p-8 text-center"><div><Workflow className="mx-auto h-7 w-7 text-cyan-200" /><h4 className="mt-3 font-bold text-white">{title}</h4><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">{detail}</p></div></section>; }
