import { Badge } from "@/components/ui/badge";
import { ArrowRight, BookOpenCheck, CheckCircle2, CircleAlert, Database, ExternalLink, Fingerprint, ShieldCheck } from "lucide-react";

export const CLIENT_GUIDE_SECTIONS = ["fontes", "caminho", "cruzamentos", "disponibilidade", "limites", "duvidas"] as const;
export const AUGUST_DATA_AVAILABILITY = {
  media: "Completo até 19/08",
  crm: "Leads e negócios até 19/08",
  rd: "Contatos BRRO e eventos coletados por API até 20/08",
} as const;

const sourceCards = [
  { source: "Google Ads", detail: "Investimento, impressões, cliques, conversões, campanhas, grupos, anúncios e URL final com tracking.", color: "cyan" },
  { source: "Meta Ads", detail: "Investimento, impressões, leads, campanhas, conjuntos, anúncios, URL de destino e url_tags.", color: "violet" },
  { source: "Bitrix24", detail: "Leads, contatos, negócios, estágios, descarte, status financeiro, UTM e identificadores de relacionamento.", color: "emerald" },
  { source: "RD Station", detail: "Contatos e eventos de conversão, com UTMs lidas da landing page ou do traffic_source decodificado nos eventos efetivamente coletados.", color: "amber" },
];

const reconciliationRows = [
  { label: "Campanha de mídia ↔ UTM do lead", evidence: "UTM campaign, term ou content contra campanha, grupo/conjunto ou anúncio importado.", rule: "Match exato; ou chave criativa normalizada; ou UTM declarada na URL da plataforma. Cada chave só é aceita se apontar para uma campanha única da mesma marca.", output: "Campanha, método de evidência e negócios associados." },
  { label: "Lead Bitrix24 ↔ negócio", evidence: "LEAD_ID explícito do negócio.", rule: "Apenas o ID armazenado no Bitrix24 é aceito. Negócios sem LEAD_ID ficam em “Não identificado”.", output: "Leads recebidos, negócios, ganhos, perdas e descartes por canal." },
  { label: "Contato Bitrix24 ↔ contato RD", evidence: "CONTACT_ID do Bitrix24 → e-mail do contato → e-mail do RD Station.", rule: "E-mail normalizado e único. Em julho, 40 leads têm match seguro; 26 e-mails duplicados e 1.981 sem chave permanecem fora do cruzamento. Telefone e CPF não têm chave utilizável nas duas fontes.", output: "Fonte, origem e UTMs dos eventos RD ligados, sem expor dados pessoais." },
  { label: "Evento RD ↔ mídia", evidence: "UTMs de landing page e identificador de campanha no evento RD Station.", rule: "A associação só é aceita se a campanha estiver registrada na camada de mídia da mesma marca e período.", output: "Evidência de origem para os eventos que chegam ao RD Station." },
];

const questions = [
  "Os leads do Bitrix24 devem receber um campo estruturado de marca? Isso eliminaria a dependência do de-para por identidade para segmentar Medsystems e BeautySystems.",
  "Telefone e CPF devem ser disponibilizados e padronizados nas duas fontes? Hoje não há chave utilizável para esse cruzamento sem risco de ambiguidade.",
  "Qual é a convenção definitiva de UTMs por canal e criativo? Padronizar campaign, term e content aumenta a cobertura de campanhas e reduz identificadores não reconciliados.",
  "A segmentação BRRO deve continuar sendo atualizada e sincronizada por API? Ela passou a sustentar a leitura de eventos RD Station em agosto até 20/08.",
  "Os negócios criados sem LEAD_ID devem ser vinculados operacionalmente ao lead de origem no Bitrix24? Sem esse ID, eles não entram na taxa de conversão por canal.",
  "Qual foi o horário de geração e quais filtros adicionais foram aplicados na exportação Bitrix24 de 19/08? A API atual contém todos os IDs exportados e 16 leads adicionais que não devem ser ocultados sem evidência.",
];

function SectionLabel({ children }: { children: React.ReactNode }) {
  return <p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-cyan-200/70">{children}</p>;
}

export function ClientDataGuide() {
  return <div className="mx-auto max-w-[1320px] space-y-6 pb-12">
    <header className="overflow-hidden rounded-3xl border border-cyan-200/15 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,.14),transparent_38%),linear-gradient(135deg,#0b1c2f,#0a1019_58%,#0a1116)] p-6 sm:p-8">
      <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="flex items-center gap-2"><BookOpenCheck className="h-4 w-4 text-cyan-200" /><SectionLabel>Guia para leitura com o cliente</SectionLabel></div><h1 className="mt-3 text-3xl font-black tracking-[-.04em] text-white sm:text-4xl">Como os dados são <span className="text-cyan-200">conectados</span></h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Esta aba explica as fontes, as regras de cruzamento e os limites de evidência do Revenue Command Center. Ela foi desenhada para apoiar uma conversa transparente com o cliente — sem transformar correlação em atribuição.</p></div><Badge variant="outline" className="w-fit border-emerald-200/20 bg-emerald-200/10 px-3 py-1.5 text-emerald-100"><ShieldCheck className="mr-1.5 h-3.5 w-3.5" />Metodologia auditável</Badge></div>
      <div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-2xl font-black text-cyan-100">4</p><p className="mt-1 text-xs text-slate-300">Fontes conectadas</p></div><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-2xl font-black text-emerald-100">3</p><p className="mt-1 text-xs text-slate-300">Níveis de evidência de campanha</p></div><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-2xl font-black text-amber-100">0</p><p className="mt-1 text-xs text-slate-300">Atribuições estimadas</p></div></div>
    </header>

    <section className="rounded-2xl border border-white/10 bg-black/15 p-5 sm:p-6"><SectionLabel>01 · Fontes e escopo</SectionLabel><h2 className="mt-2 text-xl font-bold">O que alimenta o dashboard</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-muted-foreground">Os dados de mídia vêm das contas conectadas via Windsor.ai. Bitrix24 e RD Station são mantidos como bases próprias, com registros brutos preservados para auditoria. Julho é completo nas fontes integradas; em agosto, mídia e CRM estão atualizados até 19/08, enquanto os contatos e eventos RD da segmentação BRRO estão coletados até 20/08.</p><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{sourceCards.map(item => <article key={item.source} className="rounded-xl border border-white/8 bg-white/[.025] p-4"><div className="flex items-center justify-between"><Database className={`h-4 w-4 ${item.color === "cyan" ? "text-cyan-200" : item.color === "violet" ? "text-violet-200" : item.color === "emerald" ? "text-emerald-200" : "text-amber-200"}`} /><span className="font-mono-ui text-[9px] uppercase tracking-[.12em] text-muted-foreground">Fonte</span></div><h3 className="mt-4 font-semibold text-white">{item.source}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.detail}</p></article>)}</div></section>

    <section className="rounded-2xl border border-white/10 bg-black/15 p-5 sm:p-6"><SectionLabel>02 · Caminho do dado</SectionLabel><h2 className="mt-2 text-xl font-bold">Da mídia ao resultado comercial</h2><div className="mt-5 grid gap-3 lg:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr]"><PathNode title="Mídia" detail="Campanhas, anúncios e URLs" tone="cyan" /><ArrowRight className="hidden self-center text-cyan-200/50 lg:block" /><PathNode title="Lead" detail="UTMs recebidas no Bitrix24" tone="violet" /><ArrowRight className="hidden self-center text-cyan-200/50 lg:block" /><PathNode title="Negócio" detail="LEAD_ID, estágio e descarte" tone="emerald" /><ArrowRight className="hidden self-center text-cyan-200/50 lg:block" /><PathNode title="RD Station" detail="Eventos e landing page" tone="amber" /></div><p className="mt-5 rounded-xl border border-cyan-200/10 bg-cyan-200/[.04] p-4 text-sm leading-6 text-cyan-50/80"><Fingerprint className="mr-2 inline h-4 w-4 text-cyan-200" />Cada seta representa um vínculo que precisa ser comprovado por identificador. Quando um elo não existe, o painel mostra <strong>Não identificado</strong> ou <strong>Indisponível</strong>, em vez de completar a informação por aproximação.</p></section>

    <section className="rounded-2xl border border-white/10 bg-black/15 p-5 sm:p-6"><SectionLabel>03 · Regras de cruzamento</SectionLabel><h2 className="mt-2 text-xl font-bold">Como cada associação é aceita</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-white/[.035] text-[10px] uppercase tracking-[.12em] text-muted-foreground"><tr><th className="rounded-l-xl px-4 py-3">Cruzamento</th><th className="px-4 py-3">Evidência usada</th><th className="px-4 py-3">Regra aplicada</th><th className="rounded-r-xl px-4 py-3">Resultado no painel</th></tr></thead><tbody>{reconciliationRows.map(row => <tr key={row.label} className="border-b border-white/6 last:border-0"><td className="px-4 py-4 font-semibold text-white">{row.label}</td><td className="px-4 py-4 text-xs leading-5 text-cyan-100/90">{row.evidence}</td><td className="px-4 py-4 text-xs leading-5 text-muted-foreground">{row.rule}</td><td className="px-4 py-4 text-xs leading-5 text-emerald-100/85">{row.output}</td></tr>)}</tbody></table></div></section>

    <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-black/15 p-5 sm:p-6"><SectionLabel>04 · Disponibilidade por período</SectionLabel><h2 className="mt-2 text-xl font-bold">Leitura correta do recorte temporal</h2><div className="mt-5 space-y-3"><AvailabilityRow period="Julho 2026" media="Completo" crm="Completo" rd="Eventos e contatos coletados" /><AvailabilityRow period="Agosto 2026" media={AUGUST_DATA_AVAILABILITY.media} crm={AUGUST_DATA_AVAILABILITY.crm} rd={AUGUST_DATA_AVAILABILITY.rd} /></div><p className="mt-5 text-xs leading-5 text-muted-foreground">Filtros não transformam uma fonte ausente em zero. Quando uma fonte não foi coletada, o dashboard deixa a métrica indisponível.</p></section>
      <section className="rounded-2xl border border-amber-200/15 bg-amber-200/[.025] p-5 sm:p-6"><SectionLabel>05 · Limites que preservamos</SectionLabel><h2 className="mt-2 text-xl font-bold">O que o painel não afirma</h2><ul className="mt-5 space-y-3 text-sm leading-6 text-slate-300"><li className="flex gap-3"><CircleAlert className="mt-1 h-4 w-4 shrink-0 text-amber-200" />ROAS e receita por canal não são exibidos quando não há rota completa e comprovada entre mídia, lead, negócio e venda.</li><li className="flex gap-3"><CircleAlert className="mt-1 h-4 w-4 shrink-0 text-amber-200" />Negócios sem LEAD_ID não entram na taxa de conversão por canal; eles aparecem em uma linha separada de não identificados.</li><li className="flex gap-3"><CircleAlert className="mt-1 h-4 w-4 shrink-0 text-amber-200" />Telefone e CPF não são usados no de-para atual porque não existem chaves padronizadas e utilizáveis nas duas fontes.</li><li className="flex gap-3"><CircleAlert className="mt-1 h-4 w-4 shrink-0 text-amber-200" />O KPI de leads de mídia considera somente contato RD com UTM comprovada e e-mail único. A API não expõe a composição interna dos filtros de origem da segmentação BRRO; ela não é presumida.</li><li className="flex gap-3"><CircleAlert className="mt-1 h-4 w-4 shrink-0 text-amber-200" />Nenhum dado pessoal é exibido nesta interface; apenas totais e o método de evidência.</li></ul></section></div>

    <section className="rounded-2xl border border-white/10 bg-black/15 p-5 sm:p-6"><SectionLabel>06 · Pontos para validar com o cliente</SectionLabel><h2 className="mt-2 text-xl font-bold">Perguntas que aumentam a qualidade da análise</h2><div className="mt-5 grid gap-3 lg:grid-cols-2">{questions.map((question, index) => <div key={question} className="flex gap-3 rounded-xl border border-white/8 bg-white/[.02] p-4"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-lg bg-cyan-200/10 font-mono-ui text-[10px] text-cyan-100">{String(index + 1).padStart(2, "0")}</span><p className="text-sm leading-6 text-slate-300">{question}</p></div>)}</div><div className="mt-5 flex items-center gap-3 rounded-xl border border-emerald-200/15 bg-emerald-200/[.04] p-4 text-sm text-emerald-50"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-200" />A coleta BRRO de agosto já está refletida no painel. O próximo ganho de qualidade vem de padronizar a captura no CRM, manter a segmentação atualizada e ampliar os vínculos auditáveis entre as fontes.</div></section>

    <footer className="flex flex-col justify-between gap-3 rounded-2xl border border-white/10 bg-white/[.025] p-5 text-sm text-muted-foreground sm:flex-row sm:items-center"><span>Guia de metodologia · Revenue Command Center</span><a href="#revenue" className="inline-flex items-center gap-2 font-medium text-cyan-100 hover:text-cyan-50">Voltar ao deck de Revenue <ExternalLink className="h-4 w-4" /></a></footer>
  </div>;
}

function PathNode({ title, detail, tone }: { title: string; detail: string; tone: "cyan" | "violet" | "emerald" | "amber" }) {
  const color = tone === "cyan" ? "border-cyan-200/20 text-cyan-100" : tone === "violet" ? "border-violet-200/20 text-violet-100" : tone === "emerald" ? "border-emerald-200/20 text-emerald-100" : "border-amber-200/20 text-amber-100";
  return <div className={`rounded-xl border bg-black/15 p-4 ${color}`}><p className="font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div>;
}

function AvailabilityRow({ period, media, crm, rd, warning = false }: { period: string; media: string; crm: string; rd: string; warning?: boolean }) {
  return <div className="grid gap-2 rounded-xl border border-white/8 bg-white/[.02] p-4 text-xs sm:grid-cols-4 sm:items-center"><p className="font-semibold text-white">{period}</p><p><span className="text-muted-foreground">Mídia: </span><span className="text-cyan-100">{media}</span></p><p><span className="text-muted-foreground">CRM: </span><span className="text-emerald-100">{crm}</span></p><p><span className="text-muted-foreground">RD: </span><span className={warning ? "text-amber-100" : "text-violet-100"}>{rd}</span></p></div>;
}
