import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { BarChart3, CalendarDays, CircleAlert, FileSpreadsheet, Filter, Layers3, ShieldCheck, UsersRound } from "lucide-react";
import { useState } from "react";

type BrandFilter = "all" | "medsystems" | "beautysystems";
type Metric = { label: string; count: number };

const FILTER_LABELS: Record<BrandFilter, string> = { all: "Todas as marcas", medsystems: "Medsystems", beautysystems: "BeautySystems" };
const number = (value: number) => value.toLocaleString("pt-BR");
const percent = (value: number, total: number) => total ? `${((value / total) * 100).toFixed(1).replace(".", ",")}%` : "—";

function Kpi({ label, value, helper, icon: Icon, tone = "cyan" }: { label: string; value: string; helper: string; icon: typeof UsersRound; tone?: "cyan" | "violet" | "amber" }) {
  const color = { cyan: "bg-cyan-200/10 text-cyan-100", violet: "bg-violet-200/10 text-violet-100", amber: "bg-amber-200/10 text-amber-100" }[tone];
  return <article className="rounded-2xl border border-white/10 bg-black/15 p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight text-white">{value}</p></div><span className={`grid h-9 w-9 place-items-center rounded-xl ${color}`}><Icon className="h-4 w-4" /></span></div><p className="mt-3 text-xs leading-5 text-muted-foreground">{helper}</p></article>;
}

function Ranking({ title, subtitle, rows, total, tone = "cyan" }: { title: string; subtitle: string; rows: readonly Metric[]; total: number; tone?: "cyan" | "violet" | "amber" }) {
  const max = Math.max(...rows.map(row => row.count), 1);
  const color = { cyan: "bg-cyan-300", violet: "bg-violet-300", amber: "bg-amber-300" }[tone];
  return <section className="rounded-2xl border border-white/10 bg-black/15 p-5"><p className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-muted-foreground">{subtitle}</p><h3 className="mt-1 font-semibold text-white">{title}</h3><div className="mt-5 space-y-3">{rows.map(row => <div key={row.label}><div className="mb-1.5 flex items-end justify-between gap-4 text-xs"><span className="max-w-[72%] truncate text-slate-300" title={row.label}>{row.label}</span><span className="shrink-0 font-mono-ui text-slate-100">{number(row.count)} <span className="text-muted-foreground">· {percent(row.count, total)}</span></span></div><div className="h-2 overflow-hidden rounded-full bg-white/5"><div className={`h-full rounded-full ${color}`} style={{ width: `${Math.max(2, (row.count / max) * 100)}%` }} /></div></div>)}</div></section>;
}

function DailyChart({ rows, filter }: { rows: readonly { date: string; medsystems: number; beautysystems: number }[]; filter: BrandFilter }) {
  const max = Math.max(...rows.map(row => Math.max(row.medsystems, row.beautysystems)), 1);
  const series = filter === "all" ? ["beautysystems", "medsystems"] as const : [filter] as const;
  return <section className="rounded-2xl border border-white/10 bg-black/15 p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-muted-foreground">Entrada diária</p><h3 className="mt-1 font-semibold text-white">Leads sem Evento por dia</h3></div><div className="flex items-center gap-3 text-[10px] uppercase tracking-[.12em] text-muted-foreground">{series.map(key => <span key={key} className="flex items-center gap-1.5"><i className={`h-2 w-2 rounded-full ${key === "beautysystems" ? "bg-violet-300" : "bg-cyan-300"}`} />{key === "beautysystems" ? "BeautySystems" : "Medsystems"}</span>)}</div></div><div className="mt-7 flex h-56 min-w-[600px] items-end gap-1.5 overflow-x-auto pb-6"><div className="flex h-full w-full min-w-[600px] items-end gap-1.5">{rows.map(row => <div key={row.date} className="group relative flex h-full min-w-[24px] flex-1 items-end justify-center gap-0.5">{series.map(key => <div key={key} className={`w-2 rounded-t ${key === "beautysystems" ? "bg-violet-300" : "bg-cyan-300"}`} style={{ height: `${Math.max(0, (row[key] / max) * 100)}%`, minHeight: row[key] ? "2px" : "0" }} title={`${key === "beautysystems" ? "BeautySystems" : "Medsystems"} · ${row.date}: ${row[key]}`} />)}<span className="absolute -bottom-5 left-1/2 -translate-x-1/2 text-[9px] text-muted-foreground">{row.date.slice(-2)}</span></div>)}</div></div></section>;
}

export function SpreadsheetAnalytics() {
  const [brand, setBrand] = useState<BrandFilter>("all");
  const snapshot = trpc.spreadsheet.bitrixExportDashboard.useQuery();
  if (snapshot.isLoading) return <section className="grid min-h-96 place-items-center rounded-3xl border border-cyan-200/15 bg-black/20"><p className="text-sm text-muted-foreground">Carregando a análise da planilha…</p></section>;
  if (snapshot.isError || !snapshot.data) return <section className="rounded-3xl border border-amber-200/20 bg-amber-100/5 p-8 text-center"><CircleAlert className="mx-auto h-6 w-6 text-amber-200" /><h2 className="mt-3 text-lg font-bold text-white">Não foi possível carregar a planilha</h2></section>;
  const data = snapshot.data;
  const scope = data.scopes[brand];
  const paid = scope.origins.find(row => row.label.toLowerCase() === "tráfego pago")?.count ?? 0;
  const discarded = scope.stages.filter(row => row.label.toLowerCase().includes("descartado")).reduce((sum, row) => sum + row.count, 0);
  return <div className="mx-auto max-w-[1600px] space-y-6 pb-10"><header className="overflow-hidden rounded-3xl border border-violet-200/15 bg-[radial-gradient(circle_at_top_right,rgba(167,139,250,.16),transparent_36%),linear-gradient(135deg,#111126,#0a1019_56%,#08161a)] p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><div className="flex items-center gap-2"><FileSpreadsheet className="h-4 w-4 text-violet-200" /><p className="font-mono-ui text-[10px] uppercase tracking-[.2em] text-violet-100/70">Planilha · sem leads de Evento</p></div><h1 className="mt-3 text-3xl font-black tracking-[-.045em] text-white sm:text-4xl">Leitura da <span className="text-violet-200">planilha Bitrix24</span></h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Visão exclusiva da guia <strong>Base</strong>, filtrada pelo campo <strong>Fonte</strong>. O filtro abaixo atualiza toda a leitura entre Medsystems e BeautySystems.</p></div><div className="flex flex-wrap gap-2"><Badge variant="outline" className="border-violet-200/25 bg-violet-200/10 px-3 py-1.5 text-violet-100"><FileSpreadsheet className="mr-1.5 h-3.5 w-3.5" />{data.source.fileName}</Badge><Badge variant="outline" className="border-emerald-200/25 bg-emerald-200/10 px-3 py-1.5 text-emerald-100"><CalendarDays className="mr-1.5 h-3.5 w-3.5" />{data.source.periodLabel}</Badge></div></div><div className="mt-6 flex flex-col gap-3 rounded-2xl border border-amber-200/15 bg-amber-100/[.045] p-4 text-sm leading-6 text-amber-50/85 sm:flex-row sm:items-center sm:justify-between"><p><CircleAlert className="mr-2 inline h-4 w-4 text-amber-200" /><strong>{number(data.eventExclusion.excluded)}</strong> leads com Fonte “Evento” foram retirados desta aba.</p><p className="font-mono-ui text-xs text-amber-100">{number(data.eventExclusion.remaining)} registros restantes</p></div></header>
    <section className="flex flex-wrap items-center gap-2 rounded-2xl border border-white/10 bg-black/15 p-3"><span className="mr-2 flex items-center gap-2 px-2 font-mono-ui text-[10px] uppercase tracking-[.14em] text-muted-foreground"><Filter className="h-3.5 w-3.5" />Marca</span>{(Object.keys(FILTER_LABELS) as BrandFilter[]).map(key => <button key={key} onClick={() => setBrand(key)} className={`rounded-xl px-4 py-2 text-sm transition ${brand === key ? "bg-violet-300 text-slate-950" : "bg-white/[.035] text-muted-foreground hover:bg-white/[.08] hover:text-white"}`}>{FILTER_LABELS[key]}</button>)}</section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Leads no arquivo" value={number(scope.totalLeads)} helper={`${FILTER_LABELS[brand]} · Fonte diferente de Evento`} icon={UsersRound} /><Kpi label="Período" value={`${data.period.days} dias`} helper={`${data.source.periodLabel} · data de criação`} icon={CalendarDays} tone="violet" /><Kpi label="Tráfego pago declarado" value={number(paid)} helper="Categoria Fonte da planilha; sem atribuição de plataforma" icon={BarChart3} /><Kpi label="Descartes em etapa" value={number(discarded)} helper="Soma das etapas de descarte informadas" icon={Layers3} tone="amber" /></section>
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><DailyChart rows={scope.dailyByPipeline} filter={brand} /><section className="rounded-2xl border border-white/10 bg-black/15 p-5"><p className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-muted-foreground">Pipeline de vendas</p><h3 className="mt-1 font-semibold text-white">Distribuição no filtro atual</h3><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-1">{scope.pipelines.map((pipeline, index) => <div key={pipeline.label} className="rounded-xl border border-white/8 bg-white/[.025] p-4"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${index === 0 ? "bg-violet-300" : "bg-cyan-300"}`} /><p className="text-sm font-semibold text-white">{pipeline.brand}</p></div><p className="mt-3 text-2xl font-black text-white">{number(pipeline.count)}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{pipeline.label} · {percent(pipeline.count, scope.totalLeads)}</p></div>)}</div></section></section>
    <section className="grid gap-5 xl:grid-cols-2"><Ranking title="Canais e origens declaradas" subtitle="Campo Fonte · planilha" rows={scope.origins} total={scope.totalLeads} tone="violet" /><Ranking title="Andamento dos leads" subtitle="Campo Etapa · planilha" rows={scope.stages} total={scope.totalLeads} tone="cyan" /></section>
    <section className="rounded-2xl border border-emerald-200/15 bg-emerald-100/[.035] p-5 text-sm leading-6 text-emerald-50/85"><ShieldCheck className="mr-2 inline h-4 w-4 text-emerald-200" />Esta aba utiliza somente agregações da planilha, não mostra dados pessoais e não atribui os leads a Google Ads, Meta Ads, campanha, UTM, receita ou ROAS.</section>
  </div>;
}
