import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { BarChart3, CalendarDays, CircleAlert, Database, FileSpreadsheet, Layers3, MapPinned, Sparkles, UsersRound } from "lucide-react";

type Metric = { label: string; count: number };

function integer(value: number) {
  return value.toLocaleString("pt-BR");
}

function percent(value: number, total: number) {
  return total > 0 ? `${((value / total) * 100).toFixed(1).replace(".", ",")}%` : "—";
}

function SnapshotKpi({ label, value, helper, icon: Icon, tone = "cyan" }: { label: string; value: string; helper: string; icon: typeof Database; tone?: "cyan" | "violet" | "emerald" | "amber" }) {
  const tones = {
    cyan: "bg-cyan-200/10 text-cyan-100",
    violet: "bg-violet-200/10 text-violet-100",
    emerald: "bg-emerald-200/10 text-emerald-100",
    amber: "bg-amber-200/10 text-amber-100",
  };
  return <article className="rounded-2xl border border-white/10 bg-black/15 p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight text-white">{value}</p></div><span className={`grid h-9 w-9 place-items-center rounded-xl ${tones[tone]}`}><Icon className="h-4 w-4" /></span></div><p className="mt-3 text-xs leading-5 text-muted-foreground">{helper}</p></article>;
}

function RankedBars({ title, subtitle, rows, total, accent = "cyan", limit = 8 }: { title: string; subtitle: string; rows: readonly Metric[]; total: number; accent?: "cyan" | "violet" | "emerald" | "amber"; limit?: number }) {
  const max = Math.max(...rows.slice(0, limit).map(row => row.count), 1);
  const colors = { cyan: "bg-cyan-300", violet: "bg-violet-300", emerald: "bg-emerald-300", amber: "bg-amber-300" };
  return <section className="rounded-2xl border border-white/10 bg-black/15 p-5"><p className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-muted-foreground">{subtitle}</p><h3 className="mt-1 font-semibold text-white">{title}</h3><div className="mt-5 space-y-3">{rows.slice(0, limit).map(row => <div key={row.label}><div className="mb-1.5 flex items-end justify-between gap-4 text-xs"><span className="max-w-[75%] truncate text-slate-300" title={row.label}>{row.label}</span><span className="shrink-0 font-mono-ui text-slate-100">{integer(row.count)} <span className="text-muted-foreground">· {percent(row.count, total)}</span></span></div><div className="h-2 overflow-hidden rounded-full bg-white/5"><div className={`h-full rounded-full ${colors[accent]}`} style={{ width: `${Math.max(2, (row.count / max) * 100)}%` }} /></div></div>)}</div></section>;
}

function PipelineSplit({ pipelines, total }: { pipelines: readonly { label: string; brand: string; count: number }[]; total: number }) {
  return <section className="rounded-2xl border border-white/10 bg-black/15 p-5"><p className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-muted-foreground">Pipeline de vendas</p><h3 className="mt-1 font-semibold text-white">Distribuição por marca no arquivo</h3><div className="mt-5 overflow-hidden rounded-2xl bg-white/5"><div className="flex h-4">{pipelines.map((pipeline, index) => <div key={pipeline.label} className={index === 0 ? "bg-violet-300" : "bg-cyan-300"} style={{ width: `${(pipeline.count / total) * 100}%` }} />)}</div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{pipelines.map((pipeline, index) => <div key={pipeline.label} className="rounded-xl border border-white/8 bg-white/[.025] p-4"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${index === 0 ? "bg-violet-300" : "bg-cyan-300"}`} /><p className="text-sm font-semibold text-white">{pipeline.brand}</p></div><p className="mt-3 text-2xl font-black text-white">{integer(pipeline.count)}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{pipeline.label} · {percent(pipeline.count, total)}</p></div>)}</div></section>;
}

function DailyPipelineChart({ rows }: { rows: readonly { date: string; medsystems: number; beautysystems: number }[] }) {
  const max = Math.max(...rows.map(row => Math.max(row.medsystems, row.beautysystems)), 1);
  return <section className="rounded-2xl border border-white/10 bg-black/15 p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-muted-foreground">Entrada diária</p><h3 className="mt-1 font-semibold text-white">Leads por dia e Pipeline de Vendas</h3></div><div className="flex items-center gap-3 text-[10px] uppercase tracking-[.12em] text-muted-foreground"><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-violet-300" />BeautySystems</span><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-cyan-300" />Medsystems</span></div></div><div className="mt-7 flex h-56 min-w-[600px] items-end gap-1.5 overflow-x-auto pb-6"><div className="flex h-full w-full min-w-[600px] items-end gap-1.5">{rows.map(row => <div key={row.date} className="group relative flex h-full min-w-[24px] flex-1 items-end justify-center gap-0.5"><div className="w-2 rounded-t bg-violet-300 transition-opacity group-hover:opacity-80" style={{ height: `${Math.max(2, (row.beautysystems / max) * 100)}%` }} title={`BeautySystems · ${row.date}: ${row.beautysystems}`} /><div className="w-2 rounded-t bg-cyan-300 transition-opacity group-hover:opacity-80" style={{ height: `${Math.max(2, (row.medsystems / max) * 100)}%` }} title={`Medsystems · ${row.date}: ${row.medsystems}`} /><span className="absolute -bottom-5 left-1/2 -translate-x-1/2 text-[9px] text-muted-foreground">{row.date.slice(-2)}</span></div>)}</div></div><p className="mt-2 text-xs leading-5 text-muted-foreground">O pico de 05/08 é exibido como consta na planilha: 1.636 leads em Negócios e Redes e 30 em Medsystems.</p></section>;
}

export function SpreadsheetAnalytics() {
  const snapshotQuery = trpc.spreadsheet.bitrixExportDashboard.useQuery();
  if (snapshotQuery.isLoading) return <section className="grid min-h-96 place-items-center rounded-3xl border border-cyan-200/15 bg-[linear-gradient(135deg,rgba(12,35,55,.92),rgba(12,20,35,.88))]"><div className="text-center"><FileSpreadsheet className="mx-auto h-6 w-6 animate-pulse text-cyan-200" /><p className="mt-3 text-sm text-muted-foreground">Carregando a análise da planilha…</p></div></section>;
  if (snapshotQuery.isError || !snapshotQuery.data) return <section className="rounded-3xl border border-amber-200/20 bg-amber-100/5 p-8 text-center"><CircleAlert className="mx-auto h-6 w-6 text-amber-200" /><h2 className="mt-3 text-lg font-bold text-white">Não foi possível carregar a planilha</h2><p className="mt-2 text-sm text-muted-foreground">{snapshotQuery.error?.message || "O snapshot agregado não está disponível."}</p></section>;
  const data = snapshotQuery.data;
  const declineCount = data.declineReasons.reduce((sum, row) => sum + row.count, 0);
  const technologyDeclared = data.totalLeads - (data.technologies.find(row => row.label === "Não informado")?.count ?? 0);
  const interestDeclared = data.totalLeads - (data.interests.find(row => row.label === "Não informado")?.count ?? 0);
  return <div className="mx-auto max-w-[1600px] space-y-6 pb-10">
    <header className="overflow-hidden rounded-3xl border border-violet-200/15 bg-[radial-gradient(circle_at_top_right,rgba(167,139,250,.16),transparent_36%),linear-gradient(135deg,#111126,#0a1019_56%,#08161a)] p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><div className="flex items-center gap-2"><FileSpreadsheet className="h-4 w-4 text-violet-200" /><p className="font-mono-ui text-[10px] uppercase tracking-[.2em] text-violet-100/70">Planilha · snapshot auditável</p></div><h1 className="mt-3 text-3xl font-black tracking-[-.045em] text-white sm:text-4xl">Leitura da <span className="text-violet-200">planilha Bitrix24</span></h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Visão exclusiva da guia <strong>Base</strong> enviada pelo cliente. Origens, etapas e interesses abaixo são os valores declarados na planilha, sem mistura com a coleta atual da API.</p></div><div className="flex flex-wrap gap-2"><Badge variant="outline" className="border-violet-200/25 bg-violet-200/10 px-3 py-1.5 text-violet-100"><Database className="mr-1.5 h-3.5 w-3.5" />{data.source.worksheet} · {data.source.fileName}</Badge><Badge variant="outline" className="border-emerald-200/25 bg-emerald-200/10 px-3 py-1.5 text-emerald-100"><CalendarDays className="mr-1.5 h-3.5 w-3.5" />{data.source.periodLabel}</Badge></div></div><div className="mt-6 rounded-2xl border border-violet-200/15 bg-violet-200/[.045] p-4 text-sm leading-6 text-violet-50/85"><Sparkles className="mr-2 inline h-4 w-4 text-violet-200" />{data.source.scope}</div></header>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SnapshotKpi label="Leads no arquivo" value={integer(data.totalLeads)} helper="IDs preenchidos na guia Base" icon={UsersRound} /><SnapshotKpi label="Período" value={`${data.period.days} dias`} helper={`${data.source.periodLabel} · data de criação`} icon={CalendarDays} tone="violet" /><SnapshotKpi label="Tráfego pago declarado" value={integer(data.origins.find(row => row.label === "Tráfego pago")?.count ?? 0)} helper="Categoria Fonte da planilha; não equivale a plataforma" icon={BarChart3} tone="emerald" /><SnapshotKpi label="Descartes em etapa" value={integer(data.stages.filter(row => row.label.toLowerCase().includes("descartado")).reduce((sum, row) => sum + row.count, 0))} helper="Soma das etapas de descarte informadas" icon={Layers3} tone="amber" /></section>

    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><DailyPipelineChart rows={data.dailyByPipeline} /><PipelineSplit pipelines={data.pipelines} total={data.totalLeads} /></section>

    <section className="grid gap-5 xl:grid-cols-2"><RankedBars title="Canais e origens declaradas" subtitle="Campo Fonte · planilha" rows={data.origins} total={data.totalLeads} accent="violet" /><RankedBars title="Andamento dos leads" subtitle="Campo Etapa · planilha" rows={data.stages} total={data.totalLeads} accent="cyan" limit={9} /></section>

    <section className="grid gap-5 xl:grid-cols-3"><RankedBars title="Tecnologias de interesse" subtitle={`${integer(technologyDeclared)} com tecnologia declarada`} rows={data.technologies.filter(row => row.label !== "Não informado")} total={technologyDeclared} accent="emerald" /><RankedBars title="Produtos e pontos de entrada" subtitle={`${integer(interestDeclared)} com interesse declarado`} rows={data.interests.filter(row => row.label !== "Não informado")} total={interestDeclared} accent="violet" /><RankedBars title="Perfil declarado" subtitle="Campo Segmento · planilha" rows={data.segments} total={data.totalLeads} accent="amber" limit={4} /></section>

    <section className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><RankedBars title="Distribuição geográfica" subtitle="Campo UF - PF · planilha" rows={data.states} total={data.totalLeads} accent="cyan" limit={9} /><section className="rounded-2xl border border-white/10 bg-black/15 p-5"><p className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-muted-foreground">Qualidade do preenchimento</p><h3 className="mt-1 font-semibold text-white">Cobertura dos campos disponíveis</h3><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.coverage.map((row, index) => <div key={row.label} className="rounded-xl border border-white/8 bg-white/[.025] p-4"><p className="text-xs text-muted-foreground">{row.label}</p><p className="mt-2 text-xl font-bold text-white">{integer(row.count)}</p><p className="mt-1 text-xs text-cyan-100">{percent(row.count, data.totalLeads)} preenchido</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/5"><div className={index === 0 ? "h-full bg-cyan-300" : "h-full bg-violet-300"} style={{ width: `${(row.count / data.totalLeads) * 100}%` }} /></div></div>)}</div><p className="mt-5 text-xs leading-5 text-muted-foreground">A interface não exibe os valores de telefone, empresa ou outro dado pessoal — apenas a cobertura agregada de preenchimento.</p></section></section>

    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><RankedBars title="Motivos de declínio preenchidos" subtitle={`${integer(declineCount)} registros com motivo estruturado`} rows={data.declineReasons} total={declineCount} accent="amber" limit={10} /><section className="rounded-2xl border border-amber-200/15 bg-amber-100/[.035] p-5"><p className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-amber-100/75">Limite de atribuição</p><h3 className="mt-1 font-semibold text-white">O que esta planilha não permite concluir</h3><div className="mt-5 space-y-4 text-sm leading-6 text-slate-300"><p><CircleAlert className="mr-2 inline h-4 w-4 text-amber-200" />Os campos disponíveis não trazem UTM, plataforma de mídia, ID de campanha ou vínculo mídia → venda.</p><p><CircleAlert className="mr-2 inline h-4 w-4 text-amber-200" />Por isso, “Tráfego pago” é uma origem declarada e não é repartida entre Google Ads e Meta Ads nesta aba.</p><p><CircleAlert className="mr-2 inline h-4 w-4 text-amber-200" />O campo Total não possui valor monetário agregado no arquivo; a aba não apresenta receita, ticket ou ROAS com base nele.</p></div></section></section>
  </div>;
}
